### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1130]
[https://miro.com/app/board/o9J_lZyOP0g=/](https://miro.com/app/board/o9J_lZyOP0g=/)

1. user clicks the link
   - admin-ui usermenu ddown
   - edit profile page
2. email is sent to the current user and success notification is shown
3. user clicks on the link in the email
4. user gets to a screen where she has to give her old and new passwords (new pw and confirm)
   5. if there's no error (old pw is good, new pw meets the criterias) success message is shown and the user is redirected to the admin-ui/profile as a logged-in user
   6. if the old pw is not good, or the new pw does not meet the criterias, the related error message is shown and the password should not be changed

![image](https://user-images.githubusercontent.com/6968860/100926724-2bfb2800-34e4-11eb-886d-14026cf179e8.png)

![image](https://user-images.githubusercontent.com/6968860/100926941-74b2e100-34e4-11eb-9521-0aa863b58fea.png)

**Comment by tusmester** [comment]
Proposal: 3 different actions.

### SendChangePasswordMail
Called on `Root`, accessible by anybody, even visitors. 
Sends an email to the user containing a link that leads to the pw change page on IS.
If there is no user with this email, it returns silently, no error message, because we should not tell the client if there is a user with this email or not ("If there is a user with this email in our system, we sent an email with the instructions to change your password.").
**Called from the IS Login page.**

```json
{
   "email": "user@example.com",
   "returnUrl": "https://myclientapp.com"
}
```

### SendChangePasswordMail
Called on the user, accessible by the user or anybody with `Save` permission on the user. 
Sends an email to the user containing a link that leads to the pw change page on IS.
Called from admin ui or any spa, if the user is signed in.

```json
{
   "returnUrl": "https://myclientapp.com"
}
```

### ChangePassword
Called on the user, accessible by the user or anybody with `Save` permission on the user. 
**Changes the password directly.**

```json
{
   "password": "mynewcomplexpassword"
}
```

**Comment by tusmester** [comment]
The `returnUrl` is necessary, because the repository does not know the client that the action was called from. This url is then extended with some parameters and added to the link in the email. The user will be redirected eventually to this address after changing their password in IS.

If called from the admin UI, the value of this parameter should be "https://admin.sensenet.com". If called from a different client, it should be the url of that client.
