### ISSUE TITLE
Cannot delete custom ctd 

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1609]
- get personal access token with repository owner from admin ui
- custom app create ctd with path
- on admin ui the repository owner see the created ctd as modified by Somebody
- right click action list does not appear on these ctds
- cannot delete these ctds

#### TODO
- Add See permissions for the public administrators _group_ on the public amin _user_
- simplify CTD permissions: add _Delete_ permission for more groups and register built-in types in `ContentProtector` to prevent their deletion.

**Comment by VargaJoe** [comment]
neither can be modified

**Comment by tusmester** [comment]
The reason behind the `Somebody` user is that the content was created in the name of the public administrator _user_.  Although the repo owner is in the public administrators _group_, they do not have see permissions on the public admin _user_ (these are two different things). 
We have to add more permissions (maybe members of the public admin group should be able to see the user). This issue is part of the permission/allowedtype epic. #1616
