### ISSUE TITLE
Multitenant GUI user-groups, roles, users support,

### ISSUE THREAD

**Issue by papyr** [SenseNet/sensenet#510]
Hi, how can we handle multi tenant situations in this platform

**Comment by kultsar** [comment]
Hi, @papyr, sensenet has transformed in the past year from a monolithic ECMS to a modern, modularized Content Services Platform. At present we are - among others - working on frontend components and tools and showcase apps you can use for the GUI. Part of this progress is communicated on our blog at https://community.sensenet.com/blog/. Since we are a bit lagging behind with documentation but are happy to receive early feedback, perhaps it might make sense to organize a call with you and discuss a bit more interactively. If interested, just drop us a note at https://www.sensenet.com/contact. We would be happy.

We can, of course, continue here as well if you would expand a bit more on your question.

**Comment by kultsar** [comment]
@papyr, closing this issue, but please feel free to reopen or add a new one if needed.

**Comment by papyr** [comment]
check out [ABP](https://goo.gl/Vt2utw), you may well exceed what they have, they are mostly transactional
