### ISSUE TITLE
Google Oauth login with Forms authentication

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#554]
I want to implement a 3rd party [OAuth](https://community.sensenet.com/docs/oauth/) login (e.g. Google) with sensenet, but the current implementation supports only JWT authentication and session handling.
We should implement a custom *OAuth Login endpoint / action* (similar as ``/sn-oauth/login?provider=providername``) - but for Forms authentication.

**Comment by tusmester** [comment]
Why not simply set the Forms cookie too when logging in with the current JWT api? It is not necessary to create a separate API for this. 

It would be an invalid state anyway if we allowed two different users to be logged in with these two technologies at the same time. I think it is more consistent if we set the forms cookie for the same user when they log in using the `sn-oauth` endpoint.

Maybe this behavior is something that should be configurable.

**Comment by HeroicHitesh** [comment]
@gallayl @tusmester @kultsar 
I am not sure if this issue is resolved or not but I am facing an issue of logging in/registering with my GitHub account to [SNaaS](https://is.sensenet.com/Account/Login) however I was able to login/register using my Google account.
If anyone of you can confirm that this is a new issue I'll create an issue, else if it is related to #554 only I am looking forward to a solution PR.

**Comment by herflis** [comment]
Hi @HeroicHitesh I don't think it has to do with the fact that you were not able to register/login with your GitHub account, but can you please share more detail about the issue you are facing? Maybe you could create another issue here in the repo and add the details and/or steps to reproduce. Thanks!

**Comment by tusmester** [comment]
closed as obsolete, pls open a new issue in case this comes up again
