### ISSUE TITLE
Is there a starter version now?

### ISSUE THREAD

**Issue by li0803** [SenseNet/sensenet#6]
I followed /nuget/readme.md in the source code to try Sn7.  And I download SnAdmin and compiled it and move it to SnAdminRuntime's output folder.
When I run the command: snadmin installnuget dataSource:. initialCatalog:sensenet, I got a Unhandled Exception:**System.ApplicationException: Configurae the TargetDirectory.**

**Comment by tusmester** [comment]
Wow, that was fast, thank you for trying out SN :)

We are in the process of preparing the first GitHub release of SN7. It will be a beta release, and will be available really soon - but first we have to merge our release branch(es) to the master. Currently we are testing the generated nuget package internally.

This package will contain the core layer only (without UI) that you will be able to integrate to an ASP.NET app.

SnAdmin comes as a nuget reference of this core layer (called SenseNet.Services), you do not have to compile/copy that manually.

**Comment by tusmester** [comment]
We've just published [Sense/Net Services 7.0. beta](https://github.com/SenseNet/sensenet/releases). It is a pre-release version, we plan to fix a few bugs and make some simplifications before the stable release.

Please note that this is only the "services" layer, with no UI. The next component to be published is _WebPages_, which contains the most basic UI building blocks (page creation capability, portlets, asp.net field controls) and the current admin UI, so that you will be able to access your content from the browser.

**Comment by li0803** [comment]
Thanks.
The Getting started section really help me.
