### ISSUE TITLE
Can't install SenseNet.Services 7.0 beta from internal nuget feed

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sensenet#8]
I've started to install SensenetServices from nuget but I got en error, it says: _Unable to find metadata of EntityFramework.6.1.2_

If I install EF manually I got another error:
_Unable to find metadata of SenseNet.SnAdmin.1.4.0_

I'm using visual studio 17

Should I manually install the dependencies?

**Comment by tusmester** [comment]
Could be related to this issue about not resolving dependencies across multiple sources:
https://github.com/NuGet/Home/issues/4768

(of cource this is only a temporary issue, because you are using an internal feed that will change to the official public NuGet feed on nuger.org when we release the package)

Please try to install the package with **"All"** selected as a _Package source_ in the top right corner.

If that does not help, installing the dependencies that cause the error manually should work as a workaround.

**Comment by B3zo0** [comment]
Selecting **All** in the Manage nuget packages window solved the problem. Thanks

**Comment by tusmester** [comment]
Cool! According to the linked issue above, the original problem is already solved in the dev branch of the nuget client, hope they release the new version soon :).
